execute_process(COMMAND "${CLI}" --version RESULT_VARIABLE code OUTPUT_VARIABLE text)
string(STRIP "${text}" text)
if(NOT code EQUAL 0 OR NOT text STREQUAL EXPECTED_VERSION)
    message(FATAL_ERROR "CLI version mismatch: ${code}, ${text}")
endif()
foreach(scenario IN ITEMS ok ng failure timeout)
    execute_process(COMMAND "${CLI}" --demo "${scenario}" RESULT_VARIABLE code OUTPUT_VARIABLE text)
    if(NOT code EQUAL 0)
        message(FATAL_ERROR "Demo ${scenario} command failed")
    endif()
    string(JSON state GET "${text}" result execution_state)
    string(JSON quality GET "${text}" result quality)
    if(scenario STREQUAL "ok")
        set(expected_state Completed)
        set(expected_quality OK)
    elseif(scenario STREQUAL "ng")
        set(expected_state Completed)
        set(expected_quality NG)
    elseif(scenario STREQUAL "failure")
        set(expected_state Failed)
        set(expected_quality Unknown)
    else()
        set(expected_state TimedOut)
        set(expected_quality Unknown)
    endif()
    if(NOT state STREQUAL expected_state OR NOT quality STREQUAL expected_quality)
        message(FATAL_ERROR "Demo ${scenario} result mismatch: ${state}/${quality}")
    endif()
endforeach()
execute_process(COMMAND "${CLI}" --demo overload RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 0 OR NOT text MATCHES "admitted=false\nreason=CapacityExceeded")
    message(FATAL_ERROR "Overload must be explicitly refused")
endif()
execute_process(COMMAND "${CLI}" --demo invalid RESULT_VARIABLE code OUTPUT_VARIABLE text ERROR_VARIABLE error)
if(NOT code EQUAL 2)
    message(FATAL_ERROR "Invalid demo scenario must fail")
endif()
execute_process(COMMAND "${CLI}" --status RESULT_VARIABLE code OUTPUT_VARIABLE text)
if(NOT code EQUAL 0 OR NOT text MATCHES "stage=core-foundation\ninspection_available=false\ndemo_available=true")
    message(FATAL_ERROR "CLI must clearly report the unimplemented inspection capability")
endif()
execute_process(COMMAND "${CLI}" --start-production RESULT_VARIABLE code
    OUTPUT_VARIABLE text ERROR_VARIABLE error)
if(NOT code EQUAL 2 OR NOT error MATCHES "not implemented")
    message(FATAL_ERROR "Unsupported production command must fail explicitly")
endif()
