# Optional source-tree consumer project. No mutation of framework source is needed.
set(VISION_EXTENSION_DIR "" CACHE PATH "External business project CMake directory")
if(VISION_EXTENSION_DIR)
    if(NOT IS_ABSOLUTE "${VISION_EXTENSION_DIR}")
        message(FATAL_ERROR "VISION_EXTENSION_DIR must be absolute")
    endif()
    if(NOT EXISTS "${VISION_EXTENSION_DIR}/CMakeLists.txt")
        message(FATAL_ERROR "Extension CMakeLists.txt missing")
    endif()
    file(REAL_PATH "${VISION_EXTENSION_DIR}" _vision_extension)
    file(REAL_PATH "${PROJECT_SOURCE_DIR}" _vision_root)
    if(_vision_extension STREQUAL _vision_root)
        message(FATAL_ERROR "Extension cannot be the framework root")
    endif()
    add_subdirectory("${_vision_extension}" "${PROJECT_BINARY_DIR}/user-project")
endif()
