set(VISION_JSON_INCLUDE_DIR "" CACHE PATH "Directory containing pinned nlohmann/json.hpp")
set(_json_hash "aaf127c04cb31c406e5b04a63f1ae89369fccde6d8fa7cdda1ed4f32dfc5de63")
if(NOT VISION_JSON_INCLUDE_DIR)
    if(EXISTS "${PROJECT_SOURCE_DIR}/开发环境/SDK/native/include/nlohmann/json.hpp")
        set(VISION_JSON_INCLUDE_DIR "${PROJECT_SOURCE_DIR}/开发环境/SDK/native/include")
    else()
        set(VISION_JSON_INCLUDE_DIR "${PROJECT_BINARY_DIR}/_deps/json/include")
    endif()
endif()
set(_json_header "${VISION_JSON_INCLUDE_DIR}/nlohmann/json.hpp")
if(NOT EXISTS "${_json_header}")
    if(NOT VISION_ALLOW_DOWNLOADS)
        message(FATAL_ERROR "nlohmann/json 3.12.0 missing. Set VISION_JSON_INCLUDE_DIR or VISION_ALLOW_DOWNLOADS.")
    endif()
    file(MAKE_DIRECTORY "${VISION_JSON_INCLUDE_DIR}/nlohmann")
    file(DOWNLOAD "https://raw.githubusercontent.com/nlohmann/json/v3.12.0/single_include/nlohmann/json.hpp"
        "${_json_header}" EXPECTED_HASH "SHA256=${_json_hash}" TLS_VERIFY ON TIMEOUT 60 INACTIVITY_TIMEOUT 20)
endif()
file(SHA256 "${_json_header}" _json_actual)
if(NOT _json_actual STREQUAL _json_hash)
    message(FATAL_ERROR "JSON header differs from locked nlohmann/json 3.12.0")
endif()
add_library(vision_json INTERFACE)
target_include_directories(vision_json SYSTEM INTERFACE "${VISION_JSON_INCLUDE_DIR}")
