set(VISION_DOCTEST_INCLUDE_DIR "" CACHE PATH "Directory containing doctest/doctest.h")
set(_doctest_hash "cfd518a3ef90f67e1f3ba514df23fb3627437de1a2feeba78cf5062a40021421")
if(NOT VISION_DOCTEST_INCLUDE_DIR)
    if(EXISTS "${PROJECT_SOURCE_DIR}/开发环境/SDK/native/include/doctest/doctest.h")
        set(VISION_DOCTEST_INCLUDE_DIR "${PROJECT_SOURCE_DIR}/开发环境/SDK/native/include")
    else()
        set(VISION_DOCTEST_INCLUDE_DIR "${PROJECT_BINARY_DIR}/_deps/doctest/include")
    endif()
endif()
set(_header "${VISION_DOCTEST_INCLUDE_DIR}/doctest/doctest.h")
if(NOT EXISTS "${_header}")
    if(NOT VISION_ALLOW_DOWNLOADS)
        message(FATAL_ERROR "doctest 2.5.3 missing. Set VISION_DOCTEST_INCLUDE_DIR or explicitly enable VISION_ALLOW_DOWNLOADS.")
    endif()
    file(MAKE_DIRECTORY "${VISION_DOCTEST_INCLUDE_DIR}/doctest")
    file(DOWNLOAD
        "https://raw.githubusercontent.com/doctest/doctest/v2.5.3/doctest/doctest.h"
        "${_header}" EXPECTED_HASH "SHA256=${_doctest_hash}" TLS_VERIFY ON
        TIMEOUT 60 INACTIVITY_TIMEOUT 20)
endif()
file(SHA256 "${_header}" _actual)
if(NOT _actual STREQUAL _doctest_hash)
    message(FATAL_ERROR "doctest header differs from the locked 2.5.3 artifact")
endif()
add_library(vision_doctest INTERFACE)
target_include_directories(vision_doctest SYSTEM INTERFACE "${VISION_DOCTEST_INCLUDE_DIR}")
